---
title: "16S HMC proportion modeling"
output: html_notebook
---

Read in data. 
```{r}
load("./data/Herb_PS_Objects.RData")
```

read in HMC proportions to update Time phyloseq objects 
```{r}
HMC_T1<-read.csv("./data/16S_time1_otu.csv_p_estimatesHMC.csv")
HMC_T2<-read.csv("./data/16S_time2_otu.csv_p_estimatesHMC.csv")
HMC_T3<-read.csv("./data/16S_time3_otu.csv_p_estimatesHMC.csv")
```

```{r}
# input CNVRG proportion table and it will convert to the necessary format to update a phyloseq object
format_HMC<-function(x){
  rownames(x)<-x$sample
  x1<-x[, -c(1:4)]
  x1_t<-data.frame(t(x1))
  rownames(x1_t)<-gsub("\\.", "=", rownames(x1_t))
  x1_t<-otu_table(x1_t, taxa_are_rows = T)
  return(x1_t)
}

HMC_T1_T<-format_HMC(HMC_T1)
HMC_T2_T<-format_HMC(HMC_T2)
HMC_T3_T<-format_HMC(HMC_T3)

otu_table(Time1) <- HMC_T1_T
otu_table(Time2) <- HMC_T2_T
otu_table(Time3) <- HMC_T3_T
```

Ordinate and plot via phyloseq
```{r}
#input phyloseq object
ordinate_and_plot<-function(x){
  x_ord<-phyloseq::ordinate(x, method = "NMDS", distance = "bray")
x_ord_plot<-plot_ordination(x, x_ord, type="samples", color="Herbicide")  + geom_point(size=5) + ggtitle("NMDS by Herbicie") + stat_ellipse(type = "norm", linetype = 2) + stat_ellipse(type = "t") + theme_bw() + theme(plot.title = element_text(hjust=0.5))
return(x_ord_plot)
}

#Plot to visualize seperation of soil assemblages following applicaiton
ordinate_and_plot(Time1)
ordinate_and_plot(Time2)
ordinate_and_plot(Time3)
```
Adonis testing by herbicide treatments at each time point. See https://stats.stackexchange.com/questions/314184/betadisper-is-significant-can-i-still-do-adonis-and-anosim for discussion of significant dispersion and use of adonis. 
```{r}
betadispr_adonis<-function(x){
x_dist <- phyloseq::distance(x, method = "bray")
sampledf <- data.frame(sample_data(x))
beta_mod<-betadisper(x_dist, sampledf$Herbicide)
    y1<-anova(beta_mod)
      y2<-TukeyHSD(beta_mod)
        y3<-vegan::adonis(x_dist ~ Herbicide, data = sampledf)
          y4<-pairwiseAdonis::pairwise.adonis(x_dist, sampledf$Herbicide, p.adjust.m = "bon")

          return(list(Anova = y1, Tuekys= y2, Adonis = y3, Pairwise = y4))
}

out_test<-betadispr_adonis(Time1)

dist_bray_t1 <- phyloseq::distance(Time1, method = "bray")
sampledf <- data.frame(sample_data(Time1))
beta_mod<-betadisper(dist_bray_t1, sampledf$Herbicide)
anova(beta_mod)
TukeyHSD(beta_mod)
vegan::adonis(dist_bray_t1 ~ Herbicide, data = sampledf)
pairwiseAdonis::pairwise.adonis(dist_bray_t1, sampledf$Herbicide, p.adjust.m = "bon")

```

